---
- name: Create group
  group:
    name: "{{ iib.group }}"
    state: present
  become: yes

- name: Create user
  user:
    name: "{{ iib.user }}"
    group: "{{ iib.group }}"
    state: present
  become: yes

- name: Create "{{ unarchive_dir }}"
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ iib.user }}"
    group: "{{ iib.group }}"
  become: yes
  with_items:
  - "{{ unarchive_dir }}"

- name: Unpack Archives
  unarchive: src="{{ item }}" dest="{{ unarchive_dir }}" copy=no
  with_items:
  - "{{ install_archive_path }}"
  become: yes
