---
- name: "Check required directories and files exist"
  stat: path="{{ item }}"
  register: initial_file_check
  with_items:
  - "{{ iib.archive_dir }}"
  - "{{ iib_install_archive_path }}"
  become: yes

- name: "Fail when required directories do not exist"
  fail:
    msg: "Required Installation File or Directory is missing: {{ item.item }}"
  when: "{{ item.stat.exists | bool}} == false"
  with_items: "{{ initial_file_check.results }}"

- name: Install package
  yum:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
  - unixODBC
  - unixODBC-devel

- name: Create groups
  group:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
  - "{{ iib.group }}"
  - mqbrkrs

- name: Create user
  user:
    name: "{{ iib.user }}"
    groups: "{{ iib.group }},mqbrkrs"
    state: present
  become: yes

- name: Prepare Bash profile
  template:
    dest: "/home/{{ iib.user }}/.bash_profile"
    src: ".bash_profile.j2"
    owner: "{{ iib.user }}"
    group: "{{ iib.group }}"
  become: yes

- name: Create "{{ iib.unarchive_dir }}"
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ iib.user }}"
    group: "{{ iib.group }}"
  become: yes
  with_items:
  - "{{ iib.unarchive_dir }}"

- name: Unpack Archives
  unarchive:
    src: "{{ item }}"
    dest: "{{ iib.unarchive_dir }}"
    copy: no
    owner: "{{ iib.user }}"
    group: "{{ iib.group }}"
  with_items:
  - "{{ iib_install_archive_path }}"
  become: yes

