---

- name: Accept License and Registry
  shell: "{{ item }}"
  args:
    chdir: "{{ unarchive_dir }}/{{ install_sub_dir }}"
  with_items:
  - ./iib accept license silently
  - ./iib make registry global accept license silently
  - ./iib toolkit
  - ./iib version
  become: yes

