---
#
#- name: Generate configuration file
#  template:
#    src: odbcinst.ini.j2
#    dest: "{{ iib.unarchive_dir }}/{{ iib.install_sub_dir }}/server/ODBC/unixodbc/odbcinst.ini"
#    owner: "{{ iib.user }}"
#    group: "{{ iib.group }}"
#  become: yes
#  become_user: "{{ iib.user }}"